name: Java CI

on:
   schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/5 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B compile --file my-app/pom.xml;
           mvn -B package --file my-app/pom.xml
    - uses: actions/upload-artifact@master
      with:
        name: my-artifact
        path: my-artifact

